on: [push]
name: CI
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    strategy:
      matrix:
        go-version: [1.21.x]

    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install ONNX
      run: |
        wget https://github.com/microsoft/onnxruntime/releases/download/v1.16.2/onnxruntime-linux-x64-1.16.2.tgz
        tar xf onnxruntime-linux-x64-1.16.2.tgz
        sudo cp ./onnxruntime-linux-x64-1.16.2/include/* /usr/local/include
        sudo cp ./onnxruntime-linux-x64-1.16.2/lib/* /usr/local/lib
        sudo ldconfig
    - name: Execute Tests
      run: |
        go mod download
        go mod verify
        make test
      env:
        CI: true
