name: golangci-lint
on: [push]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: [1.21.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install ONNX
        run: |
          wget https://github.com/microsoft/onnxruntime/releases/download/v1.16.2/onnxruntime-linux-x64-1.16.2.tgz
          tar xf onnxruntime-linux-x64-1.16.2.tgz
          sudo cp ./onnxruntime-linux-x64-1.16.2/include/* /usr/local/include
          sudo cp ./onnxruntime-linux-x64-1.16.2/lib/* /usr/local/lib
          sudo ldconfig
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.57.2
